apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/builder-go
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step next-version --filename package.json
        - image: gcr.io/jenkinsxio/builder-go
          name: update-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step tag --version $(cat VERSION) --no-apply
        - image: gcr.io/jenkinsxio/builder-go
          name: tag-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step tag --version $(cat VERSION)
        - image: gcr.io/jenkinsxio/jx-cli:3.0.705
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1
          name: build-dotnet-restore
          resources: {}
          script: |
            #!/bin/bash
            dotnet restore
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1
          name: build-dotnet-publish
          resources: {}
          script: |
            #!/bin/bash
            dotnet publish -c Release -o output
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1
          name: build-dotnet-assembly-name
          resources: {}
          script: |
            #!/bin/bash
            filename=$(awk -F "/" '{print $NF}'<<< $(find . -name "*.csproj" -print)); echo  ${filename%.*} > output/__assemblyname
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: promote-changelog
          resources: {}
          script: |
            #!/bin/bash
            source /workspace/source/.jx/variables.sh
            jx step changelog --batch-mode --version v${VERSION}
        - image: gcr.io/jenkinsxio/jx-cli:3.0.705
          name: promote-helm-release
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops helm release
        - image: gcr.io/jenkinsxio/jx-cli:3.0.705
          name: promote-jx-promote
          resources: {}
          script: |
            #!/bin/bash
            source /workspace/source/.jx/variables.sh
            jx promote -b --all-auto --timeout 1h --no-poll

  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
