apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: linter
  annotations:
    "lighthouse.jenkins-x.io/prependStepsURL": "https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/master/tasks/git-clone/git-clone-pr.yaml"
spec:
  stepTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    workingDir: /workspace/source
  steps:
    - env:
        - name: DOTNET_CLI_TELEMETRY_OPTOUT
          value: "true"
      image: poki712/linter-dotnet-format
      script: |
        #!/usr/bin/env bash
        dotnet help;
        echo "Starting linting";
        dotnet format --check >> linter-output.txt;
        echo "Linting finished";
      name: lint
    - script: |
        #!/usr/bin/env bash
        lines_count=$(wc -l linter-output.txt | awk '{print $1}')
        (
          if (( lines_count > 2)); then
            echo "There are problems with linting";
            jx-gitops pr comment -c "<p>There are LINT problems, see: </p><code>$(cat linter-output.txt)</code>";
            exit 1;
          else
            echo "There are NO problems with linting".
            exit 0;
          fi
        )
      image: gcr.io/jenkinsxio/jx-gitops:0.0.439
      name: pr-comment
